### ISSUE TITLE
Make this a gem

### ISSUE THREAD

**Issue by paradox460** [lmcalpin/turntable-api-rb#1]
If you don't know how i'd be happy to help. This is useful enough to go into a gem, and would help a lot of other devs out.

Just give me the word and I'll fork and make a gem

**Comment by lmcalpin** [comment]
I didn't realize anyone else used it. :)  I pushed turntable_api v 0.0.1 to rubygems.

**Comment by paradox460** [comment]
Yeah the "official" api isn't bundled right and cant be used if you install it as a gem, so… I'll use yours
